name: CI
on:
  push:
    branches:
      - '**'
env:
  NODE_ENV: ci

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run ci

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'pnpm'

      - run: pnpm install
      - run: pnpm run docs

      - uses: EndBug/add-and-commit@v9
        with:
          add: 'README.md'
          message: 'docs: update readme with latest changes'
